### ISSUE TITLE
cannot make make files 

### ISSUE THREAD

**Issue by psxpetey** [jeanthom/ibugger#2]
make[1]: arm-elf-as: Command not found

is the error I have binutils and seemingly all I need and I even set up from rockbox.sh same issue

**Comment by jeanthom** [comment]
I don't know which cross compiler you are using, but you probably have to edit the cross compiler prefix variable in each and every Makefile of the repo ("CROSS") to match what you have installed.

**Comment by psxpetey** [comment]
I tried that as well to arm-none-eabi then I found gnu tools added to path so I have arm-elf-as changed libgcc.a path to mine but same error.

**Comment by jeanthom** [comment]
I fixed a few things, https://github.com/jeanthom/ibugger/commit/a38706fbaac8a830a1b595f69b8c375cc728cf4b should work better for you.

You should call the Makefile like this:

```bash
make CROSS=arm-none-eabi- LIBGCC=/usr/lib/gcc/arm-none-eabi/11.1.0/libgcc.a
```

If you're not sure about the libgcc.a, you can use the `locate` command. I haven't found a better way to link to it yet :/

**Comment by psxpetey** [comment]
looks like that got a pass on all but ucl

```
        ^
main.c:119:6: note: expected 'uint32_t *' but argument is of type 'volatile uint32_t *'
 void decrypt(uint32_t* data, uint32_t size)
      ^
arm-none-eabi-ld -Map decryptnor.map -o decryptnor.elf init.o main.o ls.x  -Tls.x /usr/lib/gcc/arm-none-eabi/4.9.3/libgcc.a
arm-none-eabi-objcopy -O binary decryptnor.elf decryptnor.bin
make[2]: Leaving directory '/home/b/Desktop/ibug/ibugger/ipodcrypto/decryptnor'
make -C decrypt8720
make[2]: Entering directory '/home/b/Desktop/ibug/ibugger/ipodcrypto/decrypt8720'
arm-none-eabi-as -alhn=decrypt8720.lst decrypt8720.S -o decrypt8720.o
arm-none-eabi-ld -Map decrypt8720.map -o decrypt8720.elf decrypt8720.o ls.x  -Tls.x /usr/lib/gcc/arm-none-eabi/4.9.3/libgcc.a
arm-none-eabi-objcopy -O binary decrypt8720.elf decrypt8720.bin
make[2]: Leaving directory '/home/b/Desktop/ibug/ibugger/ipodcrypto/decrypt8720'
make[1]: Leaving directory '/home/b/Desktop/ibug/ibugger/ipodcrypto'
make -C ucl CC=gcc
make[1]: Entering directory '/home/b/Desktop/ibug/ibugger/ucl'
gcc -O2 -Iinclude   -c -o uclpack.o uclpack.c
gcc uclpack.o src/libucl.a -o ../uclpack
uclpack.o: In function `do_compress':
uclpack.c:(.text+0x384): undefined reference to `ucl_adler32'
uclpack.c:(.text+0x3bb): undefined reference to `ucl_malloc'
uclpack.c:(.text+0x3cb): undefined reference to `ucl_malloc'
uclpack.c:(.text+0x4b6): undefined reference to `ucl_free'
uclpack.c:(.text+0x4be): undefined reference to `ucl_free'
uclpack.c:(.text+0x50a): undefined reference to `ucl_adler32'
uclpack.c:(.text+0x566): undefined reference to `ucl_nrv2b_99_compress'
uclpack.c:(.text+0x59e): undefined reference to `ucl_nrv2d_99_compress'
uclpack.c:(.text+0x5c6): undefined reference to `ucl_nrv2e_99_compress'
uclpack.o: In function `do_decompress':
uclpack.c:(.text+0x6d1): undefined reference to `ucl_free'
uclpack.c:(.text+0x7cb): undefined reference to `ucl_adler32'
uclpack.c:(.text+0x7eb): undefined reference to `ucl_malloc'
uclpack.c:(.text+0x8da): undefined reference to `ucl_adler32'
uclpack.c:(.text+0x925): undefined reference to `ucl_adler32'
uclpack.c:(.text+0x956): undefined reference to `ucl_nrv2b_decompress_8'
uclpack.c:(.text+0x9ba): undefined reference to `ucl_nrv2d_decompress_8'
uclpack.c:(.text+0x9dd): undefined reference to `ucl_nrv2e_decompress_8'
uclpack.c:(.text+0x9fa): undefined reference to `ucl_nrv2b_decompress_safe_8'
uclpack.c:(.text+0xa17): undefined reference to `ucl_nrv2d_decompress_safe_8'
uclpack.c:(.text+0xa34): undefined reference to `ucl_nrv2e_decompress_safe_8'
uclpack.o: In function `main':
uclpack.c:(.text.startup+0x6b): undefined reference to `ucl_version_date'
uclpack.c:(.text.startup+0x72): undefined reference to `ucl_version_string'
uclpack.c:(.text.startup+0xb6): undefined reference to `__ucl_init2'
collect2: error: ld returned 1 exit status
Makefile:18: recipe for target '../uclpack' failed
make[1]: *** [../uclpack] Error 1
make[1]: Leaving directory '/home/b/Desktop/ibug/ibugger/ucl'
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 2
```

_(Moderation) I allowed myself to tweak your comment formatting to make it more readable_

**Comment by jeanthom** [comment]
Here's a workaround:

```bash
cd ucl/src
make CROSS=arm-none-eabi- LIBGCC=/usr/lib/gcc/arm-none-eabi/11.1.0/libgcc.a
```

before using `make` in the root directory

This could be fixed in ucl's Makefile, but I'm too lazy to do this

**Comment by psxpetey** [comment]
its funny i've done all these on several distros and if I didnt build arm elf using this build_arm-elf:

# Usage
# sudo ./build_arm-elf

# Setup vars
export TARGET=arm-elf
export PREFIX=/opt/gnuarmelf
export PATH=$PATH:$PREFIX/bin
export JN='-j 4'

export BINUVER=2.37

rm -rf build-*
rm -rf binutils-*

# Get archives
wget https://ftp.gnu.org/gnu/binutils/binutils-$BINUVER.tar.gz

# Extract archives
tar xf binutils-$BINUVER.tar.gz

# Build binutils
mkdir build-binutils
cd build-binutils
../binutils-$BINUVER/configure --target=$TARGET --prefix=$PREFIX
echo "MAKEINFO = :" >> Makefile
make $JN all
sudo make install
can change the BINUVER to some older version if so desired.

PATH=/opt/gnuarmelf/bin:$PATH

It always failed the whole process.
well ucl is all built now just have to test it all thanks I installed so many cross compilers and versions on different distros to make this work. Using the rockbox setup didnt work on mint as string.h ws missing god knows lol definitely should have used cygwin but i was determined lol.

**Comment by jeanthom** [comment]
Thanks for reporting this. I'm personally running Fedora Linux with whatever ARM linux toolchain I have installed a while ago.

May I ask you why you did bother to rebuild everything when all the binaries were left in the repo? :stuck_out_tongue_closed_eyes:
